### ISSUE TITLE
Incorporate anisotropic extracellular medium for point- and line-source methods

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPy#29]
`LFPy.RexExtElectrode` class and corresponding methods should be extended with anisotropic extracellular media for computing extracellular potentials

**Comment by torbjone** [comment]
Is it possible to move the method "calc_lfp_choose" from "lfpcalc.pyx" and into the "RecExtElectrode" class? If so, the method to use (calc_lfp_linesource, calc_lfp_som_as_point, calc_lfp_pointsource) would only have to be chosen once at the initiation of the RecExtElectrode class, and not for the calculation of each electrode. It would also make the cython implementation of the anisotropic methods easier, because I want sigma to be able to be either an array (sigma_x, sigma_y, sigma_z) or a scaler, and in cython (where the calc_lfp_* method is now chosen) the data type has to be specified.

**Comment by espenhgn** [comment]
@torbjone That could be an option I think. Another possibility would be that `calc_lfp_choose` takes a sigma that either is a list or double (I doubt we gain anything speedwise by typing its input parameters), and the function chooses depending on the method and sigma values between functions `calc_lfp_linesource` and `calc_lfp_linesource_w_anisotropy` etc.

In any case, the whole RecExtElectrode class implementation is kind of messy so we could consider overhauling/reimplementing anyway.

**Comment by espenhgn** [comment]
Closing, merged PR #36
